### ISSUE TITLE
Wrong playback time reported when changing to the next track

### ISSUE THREAD

**Issue by r-flash** [jmshrv/finamp#421] opened 2023-03-10 00:13 UTC
I am getting Jellyfin logs similar to the following when a track changes automatically to the next one in the playlist.
```
[2023-03-10 00:43:02.084 +01:00] [INF] [36] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Finamp" "0.6.10" playing "4 14". Stopped at "46" ms
```
Note the end: `Stopped at "46" ms`. The values are usually 0ms or 40-something.

When I stop the track manually, the reported time is correct. I suspect there might be some kind of a race condition and the playback time is reported *after* changing to the new track.

This behavior breaks scrobbling to ListenBrainz (https://github.com/lyarenei/jellyfin-plugin-listenbrainz) which probably uses a threshold for the stopping time.

**Comment by r-flash** [comment] 2023-03-10 00:33
I think I can already see the issue. If I am reading the code correctly (which is definitely not guaranteed), the following line generates playback info after the track has been switched:
https://github.com/jmshrv/finamp/blob/531625096ac23f2d2b67777f101d6c2f6a80cbdc/lib/services/music_player_background_task.dart#L100
...and `generatePlaybackProgressInfo` reads the current playback position, I believe:
https://github.com/jmshrv/finamp/blob/531625096ac23f2d2b67777f101d6c2f6a80cbdc/lib/services/music_player_background_task.dart#L386

Indeed, the same problem occurs not only on automatic track transition but also when I hit the next button.

Sadly, I haven't ever written anything in Dart and don't have the capacity to be of more help.

**Comment by r-flash** [comment] 2023-03-10 01:14
Oh and also when I change from track *n* in one album to a track *n* in a different one, nothing gets reported at all (probably because the index did not change?). Also, the track names reported after that are sometimes from the first album. Not sure if this is not a separate issue.

**Comment by Chaphasilor** [comment] 2023-03-10 09:45
Maybe there's already a PR for this: #200

**Comment by r-flash** [comment] 2023-03-10 09:53
> Maybe there's already a PR for this: #200

Thanks! I'm sorry for the duplication.

However, as the author of the PR says, it the issue that a full song duration is reported on skip. It also doesn't address the missed report when the index didn't change.

**Comment by jmshrv** [comment] 2023-03-10 12:46
Yeah, the callback where playback progress is calculated is done after a playback event is received, so when skipping it'll probably take the new postion. I really need to get #200 merged, it's been open for ages. Once that's done, I'll have a look into this (presumably, we add a special case for skipping to generate the progress info before actually skipping, and making the callback ignore skips)

**Comment by exitmouse** [comment] 2023-04-11 06:36
FYI: The plugin behavior is changing in https://github.com/lyarenei/jellyfin-plugin-listenbrainz/pull/26. That PR will allow Finamp to scrobble if you use the alternative listen recognition mode--there are some potential drawbacks, though. I'm not familiar enough with Finamp architecture to know whether it will work consistently, but currently it's working for me.

**Comment by csaavedra** [comment] 2023-06-02 08:37
> FYI: The plugin behavior is changing in [lyarenei/jellyfin-plugin-listenbrainz#26](https://github.com/lyarenei/jellyfin-plugin-listenbrainz/pull/26). That PR will allow Finamp to scrobble if you use the alternative listen recognition mode--there are some potential drawbacks, though. I'm not familiar enough with Finamp architecture to know whether it will work consistently, but currently it's working for me.

IIUC this won't solve the issue of last.fm tracks not getting scrobbled by finamp, so I suppose it would make sense to fix this anyway so that any scrobbling service works.

**Comment by csaavedra** [comment] 2023-06-13 13:24
It seems to me that the main cause of this is a limitation in the information that the background task has available from the audio player. Ideally, the background task would also receive events pertaining playback ending for a given track, before going to the next, so that the background task can handle it before the playback of the next track starts. Maybe that exists and it's possible to do it, but I am not familiar with the codebase or how this works so I couldn't really figure it out.

In the meantime, I figured that one way to have *some* degree of correctness would be to actually keep track of the last known playback info for the current track, so that when the next track starts, we can use the saved playback info instead of generating one that is by no means correct. I am not making a merge request because the code I am attaching is untested and very likely not working, but it should give an idea of how to solve this. Keep in mind that I don't know anything about dart or finamp beyond having read the code for about half an hour, but hopefully this can stear things in the right direction to solve this.

```diff
diff --git a/lib/services/music_player_background_task.dart b/lib/services/music_player_background_task.dart
index 8d6227d..8eb2517 100644
--- a/lib/services/music_player_background_task.dart
+++ b/lib/services/music_player_background_task.dart
@@ -44,8 +44,10 @@ class MusicPlayerBackgroundTask extends BaseAudioHandler {
   /// new queue.
   int? nextInitialIndex;
 
-  /// The item that was previously played. Used for reporting playback status.
-  MediaItem? _previousItem;
+  /// The item that we are currently playing and its playback progress info.
+  //// Used for reporting playback status when the track changes.
+  MediaItem? _currentItem;
+  PlaybackProgressInfo? _currentlyPlayingPlaybackInfo;
 
   /// Set to true when we're stopping the audio service. Used to avoid playback
   /// progress reporting.
@@ -96,14 +98,8 @@ class MusicPlayerBackgroundTask extends BaseAudioHandler {
       if (!FinampSettingsHelper.finampSettings.isOffline) {
         final jellyfinApiHelper = GetIt.instance<JellyfinApiHelper>();
 
-        if (_previousItem != null) {
-          final playbackData = generatePlaybackProgressInfo(
-            item: _previousItem,
-            includeNowPlayingQueue: true,
-          );
-
-          if (playbackData != null) {
-            await jellyfinApiHelper.stopPlaybackProgress(playbackData);
+        if (_currentItem != null && _currentlyPlayingPlaybackInfo != null) {
+            await jellyfinApiHelper.stopPlaybackProgress(_currentlyPlayingPlaybackInfo);
           }
         }
 
@@ -117,7 +113,11 @@ class MusicPlayerBackgroundTask extends BaseAudioHandler {
         }
 
         // Set item for next index update
-        _previousItem = currentItem;
+        _currentItem = currentItem;
+        _currentlyPlayingPlaybackInfo = generatePlaybackProgressInfo(
+          item: currentItem,
+          includeNowPlayingQueue: false,
+        );
       }
     });
 
@@ -490,10 +490,10 @@ class MusicPlayerBackgroundTask extends BaseAudioHandler {
     try {
       JellyfinApiHelper jellyfinApiHelper = GetIt.instance<JellyfinApiHelper>();
 
-      final playbackInfo =
+      _currentlyPlayingPlaybackInfo =
           generatePlaybackProgressInfo(includeNowPlayingQueue: false);
-      if (playbackInfo != null) {
-        await jellyfinApiHelper.updatePlaybackProgress(playbackInfo);
+      if (_currentlyPlayingPlaybackInfo != null) {
+        await jellyfinApiHelper.updatePlaybackProgress(_currentlyPlayingPlaybackInfo);
       }
     } catch (e) {
       _audioServiceBackgroundTaskLogger.severe(e);
```

**Comment by Chaphasilor** [comment] 2023-06-13 22:07
> Ideally, the background task would also receive events pertaining playback ending for a given track, before going to the next, so that the background task can handle it before the playback of the next track starts. Maybe that exists and it's possible to do it, but I am not familiar with the codebase or how this works so I couldn't really figure it out.

Sadly, `just_audio` is pretty inflexible and opinionated. I've tried doing just that for almost two weeks while rewriting the queuing system, but in the end I gave up and let `just_audio` manage everything. I really don't like it, but it's been the most reliable solution, sadly.  

However, I think the new queue system will fix this issue, because the code is less convoluted overall and more purpose-made for handling changes of the current track :)

**Comment by Chaphasilor** [comment] 2024-02-28 13:51
@r-flash @csaavedra playback reporting has been improved as part of the redesign beta. I did implement a separate service that implements your suggestion for remembering the currently playing track to make things (hopefully) more reliable. You can check it out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved. Please let me know if you still have issues with this!

**Closed by Chaphasilor** 2024-02-28 13:51 UTC

**Comment by Titaniumtown** [comment] 2025-01-26 06:33
I can reproduce this issue on the redesign branch. It's very annoying and random
