### ISSUE TITLE
[Feature Request] Carplay App/UI

### ISSUE THREAD

**Issue by imstupidwithlinux** [jmshrv/finamp#912] opened 2024-10-02 17:54 UTC
Im very pleased with the current redesign and new functions that have been added in the beta but now that i have a fancy new radio in my car im kinda missing the app on there. Theres spotify of course but finamp is just straightup better.

**Comment by Chaphasilor** [comment] 2024-10-03 17:49
Duplicate of #24 :)

**Closed by Chaphasilor** 2024-10-03 17:49 UTC
