### ISSUE TITLE
Download all missing songs on playlist/album

### ISSUE THREAD

**Issue by pedrotrschneider** [jmshrv/finamp#328] opened 2022-09-20 19:56 UTC
If I create a playlist and download it, I can play it normally in offline mode. However, if I then add a new song to the playlist, it no longer appears in offline mode, as if it was never downloaded. Furthermore, there is no option to download the single song I added to the playlist, and I need to delete all other downloaded songs, and then download the entire playlist again.

Is this an actual bug or am I missing something? I am aware of #213, but I didn't see this specific issue mentioned there, or anywhere else, that's why I'm opening this one.

If this is actually a bug, I would suggest either adding a "download all missing songs on playlist/album" button alongside the "delete downloads" button, or identifying when a downloaded playlist has tracks that are not downloaded and change the "delete downloads" button to a "download missing tracks" button. I prefer the first option, since the second option would make it impossible to delete all tracks on the playlist without downloading the rest of them first, but maybe something in-between would be a good idea.

Another option to mitigate this issue would be to make the "downloaded" property local to tracks. I think this would be a good idea. Right now, I have to either download the entire album/playlist or create another playlist if I want to listen to some of the songs in an album/playlist. If there are any downloaded tracks in a playlist/album, I think they should already show up in offline mode, and not require all songs to be downloaded.

**Comment by Y0ngg4n** [comment] 2022-09-21 19:41
It is missing. But i am currently working on a pull request to enhance the downloads. Maybe just wait.

**Comment by Demian98** [comment] 2022-09-21 20:24
@Y0ngg4n It would be great if your enhancements would also include an option to restart failed downloads. Currently we also need to delete an redownload the full album in case one download fails.

**Comment by Y0ngg4n** [comment] 2022-09-21 20:41
@Demian98 that is exactly what i try to implement currently

**Comment by Y0ngg4n** [comment] 2022-09-22 11:23
#331

**Comment by seniorm0ment** [comment] 2022-12-12 15:59
I do encounter this as well, was curious if there was any updates on it?
If I add a new song to a playlist it doesn't automatically download it if I previously downloaded that playlist.

**Comment by JPinSPACE** [comment] 2023-04-19 16:34
I just wanted to add my voice saying that this is still a problem. I maintain a lengthy "general" playlist to throw on shuffle while in the car. But any time I add anything to the playlist if I want it to work in offline mode I have to delete the playlist and allow it to redownload, which usually takes a couple of attempts and uses so much data that I can only do it on wifi.

**Comment by Y0ngg4n** [comment] 2023-04-19 18:09
@JPinSPACE do you tried the retry downloads button in the downloads page?

**Comment by JPinSPACE** [comment] 2023-04-20 01:35
I just tried it. It just says I don't have any download errors. It's not an error per se, it's just that the playlist now has extra songs at the end and in the past I had downloaded the playlist. The expected behavior is that the playlist would understand its status as "downloaded", see that it now has undownloaded songs on the end and then download them.

**Comment by Y0ngg4n** [comment] 2023-04-22 14:20
@JPinSPACE ah ok. so you added more items to the playlist and they did not got auto downloaded?

**Comment by JPinSPACE** [comment] 2023-04-22 15:39
Yep, correct

**Comment by Y0ngg4n** [comment] 2023-04-22 20:39
> Yep, correct

i think that is a case not covered yet. Please create a seperate issue describing the problems in detail and link this issue please. Thx.

**Comment by JPinSPACE** [comment] 2023-04-23 23:13
Ahh, gotcha, will do, thanks.

**Comment by Venryx** [comment] 2023-09-23 22:28
Hitting the same issue, where I add one song to a previously-downloaded album (which is really just a container folder on my desktop/server), and I'm unable to append it to my downloading songs without deleting the whole thing first then redownloading from scratch.

The code in question seems to be here: https://github.com/jmshrv/finamp/blob/0b3857490f266afd7402077dabdd8b370a0cdad3/lib/components/AlbumScreen/download_button.dart#L43-L56

The work needed I guess would be to improve the `isAlbumDownloaded` function to return more granular results than just "is downloaded or not", and then make similar granularity adjustments to the code that does the downloading for the album (if not done already).

**Comment by Venryx** [comment] 2023-09-24 00:05
Oh, I see that someone created a pull-request for another way to solve this issue!: https://github.com/jmshrv/finamp/pull/460

Not sure which approach is better, but since one is already written and ready to go, that seems preferable. (and anyway, it'd be possible to implement a second way to update it later)

**Comment by Chaphasilor** [comment] 2023-12-11 18:18
#534 will add a button in each playlist that will synchronize all songs (download new ones, delete removed ones if they're not part of another downloaded playlist/album). This should close the issue.

It's not automatic (yet), but we'll get there!

**Closed** 2023-12-24 14:48 UTC
