### ISSUE TITLE
Cant play downloaded items in playlist if playlist contains download errors

### ISSUE THREAD

**Issue by Y0ngg4n** [jmshrv/finamp#344] opened 2022-10-05 10:33 UTC
Expected: Ignore the failed downloads and play only the downloaded.

How it is currently:
You cant play any song of the playlist. Neither via Shuffle, Play or by tapping on the songs.

**Comment by Chaphasilor** [comment] 2022-10-05 15:34
Duplicate of #252

**Closed** 2022-10-05 16:50 UTC
