### ISSUE TITLE
120hz support on iOS?

### ISSUE THREAD

**Issue by Sukuratchi** [jmshrv/finamp#455] opened 2023-06-09 09:50 UTC
App runs at 60fps on 120hz capable iPhones

**Comment by jmshrv** [comment] 2023-06-09 22:30
This is caused by Finamp not having `CADisableMinimumFrameDurationOnPhone` set to `true` in `Info.plist`, as new Flutter apps do by default. I'll fix it for the next release :)

**Comment by jmshrv** [comment] 2023-07-30 14:22
Forgot to put it in 0.6.15, fixed now in e86c5d7

**Closed by jmshrv** 2023-07-30 14:22 UTC
