### ISSUE TITLE
The shuffle button only plays from the first one at playlist

### ISSUE THREAD

**Issue by yuruxuan** [jmshrv/finamp#391] opened 2023-01-28 09:52 UTC
During my use, I found that every time I click the shuffle button, the first music is always the first song in the playlist every time. Starting from the second song, random music will play.

I checked the code and found that the shuffle function directly calls the just_audio library. At the same time, I found that the [shuffle()](https://pub.flutter-io.cn/documentation/just_audio/latest/just_audio/DefaultShuffleOrder-class.html) method can pass an initial position parameter. See if this information is helpful to solve this problem?

I haven't read the entire project code completely, and direct modification may introduce new bugs.

```
@override
  Future<void> setShuffleMode(AudioServiceShuffleMode shuffleMode) async {
    try {
      switch (shuffleMode) {
        case AudioServiceShuffleMode.all:
          await _player.shuffle(); ///////////////////// Maybe need initialIndex params
          await _player.setShuffleModeEnabled(true);
          shuffleNextQueue = true;
          break;
        case AudioServiceShuffleMode.none:
          await _player.setShuffleModeEnabled(false);
          shuffleNextQueue = false;
          break;
        default:
          return Future.error(
              "Unsupported AudioServiceRepeatMode! Recieved ${shuffleMode.toString()}, requires all or none.");
      }
    } catch (e) {
```

**Comment by Chaphasilor** [comment] 2023-01-28 10:37
there's already an issue for this: #61

it seems to be a problem with `just_audio`

**Comment by jmshrv** [comment] 2023-01-29 05:46
Duplicate of #61

**Closed by jmshrv** 2023-01-29 05:46 UTC

**Comment by jmshrv** [comment] 2023-01-29 05:47
I'll try messing about with initialIndex :)
