### ISSUE TITLE
CrossFade Feature

### ISSUE THREAD

**Issue by waynepaulward** [jmshrv/finamp#353] opened 2022-11-04 13:59 UTC
Will the crossfade function ever be available 
Even if just for downloaded tracks 
I use the play sub app with my airsonic server when i need to crossfade my playlists 
If you can add this feature ill dump the airsonic and just use finamp 
This would be fantastic 
Love the player its a daily runner

**Comment by jmshrv** [comment] 2022-11-18 22:45
Duplicate of #237, will explain the state of this issue there :)

**Closed by jmshrv** 2022-11-18 22:45 UTC
