### ISSUE TITLE
Expanded track details panel doesn't render background completely

### ISSUE THREAD

**Issue by Maxr1998** [jmshrv/finamp#744] opened 2024-05-23 23:44 UTC
When long pressing a track and then expanding the bottom sheet, the background doesn't cover the whole sheet and is instead black translucent.

<details>
<summary>Screenshot</summary>

![Screenshot](https://github.com/jmshrv/finamp/assets/5903699/c4e68d3c-7373-492b-8573-ded323a8d245)
</details>

**Comment by Chaphasilor** [comment] 2024-05-24 00:12
This only happens when not on the player screen. The playlist actions menu is also affected.

**Comment by Chaphasilor** [comment] 2024-05-24 00:13
@Komodo5197 I guess this broke when switching to using the generic menu. Mind taking a look?

**Comment by Komodo5197** [comment] 2024-05-24 01:15
This is most likely related to the CachePaint widget not redrawing with the new size correctly.  It doesn't seem to be reproducing for me though?

**Comment by Chaphasilor** [comment] 2024-05-24 07:25
I only have the issue in the release build on Android. Could that be it?

**Comment by Komodo5197** [comment] 2024-05-24 07:32
Maybe?  I’ll try a release build later.

**Comment by Chaphasilor** [comment] 2024-07-29 14:11
Closing since this has been fixed a while ago :)

**Closed by Chaphasilor** 2024-07-29 14:11 UTC
Labels: bug, design, high priority, redesign-beta
