### ISSUE TITLE
500 Error when transcoding

### ISSUE THREAD

**Issue by JVT038** [jmshrv/finamp#396] opened 2023-02-01 15:38 UTC
When I have Wi-Fi and play a song that isn't downloaded, it throws an error in the Jellyfin server logs:
```
[2023-02-01 16:29:01.487 +01:00] [ERR] [19] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HMNT9JQ25S0S"", Request id ""0HMNT9JQ25S0S:0000000C"": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too many bytes written (177545 of 177251).
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.VerifyAndUpdateWrite(Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WritePipeAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionBody.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.StreamCopyOperationInternal.CopyToAsync(Stream source, Stream destination, Nullable`1 count, Int32 bufferSize, CancellationToken cancel)
   at Microsoft.AspNetCore.Internal.FileResultHelper.WriteFileAsync(HttpContext context, Stream fileStream, RangeItemHeaderValue range, Int64 rangeLength)
   at Microsoft.AspNetCore.Mvc.Infrastructure.FileResultExecutorBase.WriteFileAsync(HttpContext context, Stream fileStream, RangeItemHeaderValue range, Int64 rangeLength)
   at Microsoft.AspNetCore.Mvc.Infrastructure.FileStreamResultExecutor.ExecuteAsync(ActionContext context, FileStreamResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jellyfin.Server.Middleware.BaseUrlRedirectionMiddleware.Invoke(HttpContext httpContext, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
The logcat gives this:
```
02-01 16:37:21.554  4041  4041 E AudioPlayer: TYPE_SOURCE: Input does not start with the #EXTM3U header.
02-01 16:37:21.562  4041  4041 I ExoPlayerImpl: Release 4cad1ac [ExoPlayerLib/2.18.1] [FP4, FP4, Fairphone, 32] [goog.exo.core, goog.exo.exoplayer, goog.exo.decoder, goog.exo.hls, goog.exo.datasource]
02-01 16:37:29.176  4041  4041 I ExoPlayerImpl: Init 534c5e3 [ExoPlayerLib/2.18.1] [FP4, FP4, Fairphone, 32]
02-01 16:37:29.200  4041  4066 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(0, Source error, null, null)
02-01 16:37:29.200  4041  4066 E flutter :
02-01 16:37:33.103  4041  4386 E ExoPlayerImplInternal: Playback error
02-01 16:37:33.103  4041  4386 E ExoPlayerImplInternal:   n0.q: Source error
02-01 16:37:33.103  4041  4386 E ExoPlayerImplInternal:       at n0.n1.H(Unknown Source:16)
02-01 16:37:33.103  4041  4386 E ExoPlayerImplInternal:       at n0.n1.handleMessage(Unknown Source:322)
02-01 16:37:33.103  4041  4386 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
02-01 16:37:33.103  4041  4386 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:201)
02-01 16:37:33.103  4041  4386 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:288)
02-01 16:37:33.103  4041  4386 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
02-01 16:37:33.103  4041  4386 E ExoPlayerImplInternal:   Caused by: n0.m2: Input does not start with the #EXTM3U header.
02-01 16:37:33.103  4041  4386 E ExoPlayerImplInternal:       at v1.j.i(Unknown Source:172)
02-01 16:37:33.103  4041  4386 E ExoPlayerImplInternal:       at v1.j.a(Unknown Source:0)
02-01 16:37:33.103  4041  4386 E ExoPlayerImplInternal:       at i2.j0.a(Unknown Source:31)
02-01 16:37:33.103  4041  4386 E ExoPlayerImplInternal:       at i2.h0$d.run(Unknown Source:51)
02-01 16:37:33.103  4041  4386 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-01 16:37:33.103  4041  4386 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-01 16:37:33.103  4041  4386 E ExoPlayerImplInternal:       at java.lang.Thread.run(Thread.java:920)
```

**Comment by jmshrv** [comment] 2023-02-01 17:38
This looks like some weird HLS issue. Are you playing with transcoding enabled?

**Comment by JVT038** [comment] 2023-02-01 18:55
Yes; without the transcoding the issue disappears

**Comment by jmshrv** [comment] 2023-02-01 20:46
Could you send the file that you're trying to play? It would help massively with debugging :)

**Comment by jmshrv** [comment] 2023-02-09 10:20
Oh - random idea (will test in a minute) - Finamp has some weird behaviour around transcoding stuff with a low bitrate (#269), maybe the same thing is happening here

**Comment by jmshrv** [comment] 2023-02-10 17:10
Reproduced, looks like a duplicate of #269. If your source is high-bitrate (higher than your transcoding bitrate), let me know since it will then be a separate issue.

**Closed by jmshrv** 2023-02-10 17:10 UTC
