### ISSUE TITLE
Finamp not starting-splash screen message

### ISSUE THREAD

**Issue by Purplemonsta** [jmshrv/finamp#828] opened 2024-07-30 15:15 UTC
Hi 

Got an issue while starting up Finamp in linux mint 21.3
screenshot of splash window attached
Also copied logs from said window below

Any ideas??
![Screenshot from 2024-07-30 16-12-25](https://github.com/user-attachments/assets/c42d99d8-5764-411d-b9df-e14c802f4b0d)

[Startup/INFO] 2024-07-30 16:07:45.606460: App starting, logging initialized.
[ErrorApp/SEVERE] 2024-07-30 16:07:45.628297: type 'bool' is not a subtype of type 'LyricsAlignment' in type cast
		#0      FinampSettingsAdapter.read (package:finamp/models/finamp_models.g.dart:173)
		#1      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:328)
		#2      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:276)
		#3      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
		#4      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
		<asynchronous suspension>
		#5      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
		<asynchronous suspension>
		#6      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
		<asynchronous suspension>
		#7      HiveImpl.openBox (package:hive/src/hive_impl.dart:142)
		<asynchronous suspension>
		#8      Future.wait.<anonymous closure> (dart:async/future.dart:524)
		<asynchronous suspension>
		#9      setupHive (package:finamp/main.dart:221)
		<asynchronous suspension>
		#10     main (package:finamp/main.dart:80)
		<asynchronous suspension>

**Comment by jmshrv** [comment] 2024-07-30 16:30
Duplicate of #824 - you'll need to do a clean install of Finamp

**Closed by jmshrv** 2024-07-30 16:30 UTC
