### ISSUE TITLE
All layout oriented from right to left

### ISSUE THREAD

**Issue by AdrienLombard** [jmshrv/finamp#314] opened 2022-08-27 19:22 UTC
Since I updated to Finamp 0.6.6, all the layout is oriented as if my phone was set to a right-to-left language (like arabic).
Moreover, some text in arabic does now appears in some popups.

My phone is set to French and I know that Android 13 that I'm using allows to set per-app localization settings, but I didn't noticed anything about Finamp in those settings. Whatever maybe is it related to that.

Interestingly enough, the problem disappears if I reinstall Finamp 0.6.5.

You can find some screenshots here : 
[https://ibb.co/H4Gp8DL](https://ibb.co/H4Gp8DL)
[https://ibb.co/ygW1cms](https://ibb.co/ygW1cms)
[https://ibb.co/pxBh914](https://ibb.co/pxBh914)
[https://ibb.co/Bfmv3px](https://ibb.co/Bfmv3px)

Phone : Google Pixel 6
Android version : 13
Finamp version : 0.6.6

**Comment by jmshrv** [comment] 2022-08-27 22:03
Duplicate of #313

**Closed** 2022-08-27 22:03 UTC
