### ISSUE TITLE
"Add to Playlist" allows for duplicates

### ISSUE THREAD

**Issue by Emporea** [jmshrv/finamp#438] opened 2023-04-23 17:27 UTC
Adding a song to a playlist that is already present in the playlist adds it another time.

finamp: 0.6.12 fdroid
jellyfin. 10.8.9

Playlists and Jellyfin is a weird topic in general. But Jellyfin WebUI doesn't add an existing song again to a playlist nor prompts the user tho.... And having duplicates through finamp doesn't seem to bother Jellyfin.

So it would be nice to not add duplicates via finamp. If its too difficult to add a toast its also fine if it just silently doesn't add songs another time ( like Jellyfin web ui does... )

**Comment by jmshrv** [comment] 2023-04-24 02:04
I'd say this is intended behaviour, other apps like Spotify let you have duplicates in playlists

**Comment by Chaphasilor** [comment] 2023-04-24 07:27
I agree, but a confirmation prompt would be nice to have, because otherwise there's no way to know if a song is already in a playlist or not...

**Comment by seniorm0ment** [comment] 2023-05-27 16:06
This could be resolved with a simple client side option users can click edit playlist and then click remove duplicates. 
Jellyfin does lack this server side too yes.

**Comment by Chaphasilor** [comment] 2024-11-13 14:34
Newer versions of Jellyfin don't seem to allow duplicates in playlists anymore.  
Also, the beta version will now automatically fetch playlist information on startup and will mark tracks as already added to a playlists when selecting such a track. So adding duplicates is very unlikely now.

**Closed by Chaphasilor** 2024-11-13 14:34 UTC
Labels: good first issue, hacktoberfest
