### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [jmshrv/finamp#359] opened 2022-11-15 05:02 UTC
https://monitor.f-droid.org/builds/log/com.unicornsonlsd.finamp/26#site-footer

Could you please take a look? Thanks!

By the way, could you please add flutter as a git submodule so that we can use that directly without taking care of the flutter version in the build metadata?

**Comment by jmshrv** [comment] 2022-11-16 22:40
(Thought I replied to this, must have forgot to send 🙃)

The build issue has been fixed (#360), I'll set up Flutter as a submodule and make a +1 build for F-Droid :)

**Comment by linsui** [comment] 2022-11-17 02:15
Thanks!

**Comment by jmshrv** [comment] 2022-11-18 22:44
Thank you for manually doing a workaround on the F-Droid side, the root cause of the issue has been fixed in 5aaa20a3033abab5e33122bebdceac289dbe9219

**Closed by jmshrv** 2022-11-18 22:44 UTC
