### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by Fale** [jmshrv/finamp#592] opened 2024-02-09 17:03 UTC
Hi,

I was downloading some music (~40Gb) from Jellyfin to Finamp. During the download I closed the application.
At the following start of the application I can only see this:

![Screenshot_20240209_180014](https://github.com/jmshrv/finamp/assets/77888/98e9aa4d-3911-41b6-9b34-d0d07e7a788c)

Closing and reopening the app, the same message appears.

I'm running Finamp 0.6.18 downloaded from F-Droid on a Samsung Galaxy S22 with Android 14.

**Comment by Chaphasilor** [comment] 2024-02-09 23:47
Okay that is really strange 😅

Can you go into the system settings for the Finamp app and check how much storage the app is using? Should look something like this:  
![Screenshot_20240210-004519_Settings.png](https://github.com/jmshrv/finamp/assets/18015147/5a16ed19-4e1f-498f-9d5c-ec73558f0a5b)

There you can also clear the app data and log into Jellyfin again, and then you can retry your download. You'll "lose" your Finamp setting, but that's probably not an issue.

May I ask what you're downloading? A very large playlist? FLACs?

**Comment by Fale** [comment] 2024-02-10 07:33
I'm downloading a 1.5k FLAC songs playlist.

This is how that screen looks:
![Screenshot_20240210_082938_Settings](https://github.com/jmshrv/finamp/assets/77888/636af249-e2d1-445e-805b-caac5cf20f2b)

Doing a "clear data" the application resets but it starts working again.

This same issue already happened another time to me, and this time I wanted to report it before cleaning the data :).

**Comment by Chaphasilor** [comment] 2024-02-10 12:03
Alright, yeah the old download system isn't the best. If you feel like it, you could try out the new downloading system. It will be released as part of the redesign beta shortly, but some early testing with previously problematic use cases like your would be nice!

You can downloaded the preliminary APK from here: https://gofile.io/d/dcsOfb

You'll have to uninstall the old version first, since this new APK is signed by me instead of James, and Android will (rightfully) complain about it. There's now also the option to downloaded transcoded copies of your files, e.g. as 64kbps OPUS, which should significantly reduce the size of your downloads. You can also try that, but please first try the regular downloads and see if it's working correctly :)

**Comment by Fale** [comment] 2024-02-10 14:35
Thanks!

I've tried the new version without transcoding. The download did not managed to download all elements at the first shot (after ~3500 downloads it was saying 0 enqueued, 0 running), so I did a "sync (the two arrows in circle in the top right area in the download page) and it detected and downloaded the missing items.
The application is now working as expected both online and offline mode :).

I'll try removing them and re-downloadedin with the transcoding feature now.

**Comment by Chaphasilor** [comment] 2024-02-10 15:18
After 3.5k downloads it stopped downloading? Aren't there just 1.5k songs in the playlist? Even with the album covers it shouldn't be that many downloads to begin with...

And if you could grab the logs if this issue (with the missing downloads) appears again, that would be fantastic. Just go to the "Logs" section and click the share icon, then save the file somewhere and attach it here :)

**Comment by Fale** [comment] 2024-02-10 15:30
I have no idea where all those download comes from. The "correct" number of download (with all stuff correctly downloaded) is 3710 for a 1612 songs.

I've enabled the transcoding and started again. This time all 3710 items got properly identified. It could have been a transient thing.
From the log it does not show any error in the syncing phase.
As for log uploading, it feel a little too full of data to upload it anywhere ;-).

Thanks a lot, these changes make a massive difference to Finamp!

**Comment by Chaphasilor** [comment] 2024-02-10 16:02
Ahh, it's probably songs + album images + artist images (artists are also supported in offline mode now). Album metadata is also downloaded, you should see that when going into offline mode and opening an abum where not all songs have been downloaded yet.

It's great to hear that downloading is working well for you, at least for the most part. And most importantly, it's not crashing anymore 😁

Just out of curiosity, how much storage is required to download the whole playlist in original quality vs transcoded?

**Comment by Fale** [comment] 2024-02-10 17:51
There is a very strange thing I've noticed. When downloading FLAC, the "data" increase, while when I download transcoded OPUS (320kbps in my case) the "cache" amount increase. Those are the two screenshots:

![Screenshot_20240210_163352_Settings](https://github.com/jmshrv/finamp/assets/77888/e730425f-426b-422a-b3f9-63cc71544cfd)
![Screenshot_20240210_175614_Settings](https://github.com/jmshrv/finamp/assets/77888/65655771-7a51-4627-a883-96434570f851)

**Comment by Chaphasilor** [comment] 2024-02-10 19:28
Thanks for pointing that out. Before the transcoding changes everything was added to "Data" as far as I'm aware, not sure why that has changed.  

Maybe @Komodo5197 knows why this is happening?

**Comment by Komodo5197** [comment] 2024-02-11 03:37
As far as I'm aware, downloads to the documents directory show up as data, but downloads to the application support directory show up as cache.  Documents was the old default, application support is the new default.  If you had migrated downloads it might have still been using their download ID but cleared it out when you deleted things to download the transcodes  If this was a totally clean install then I'm not sure what would be causing this.  In my testing, the downloads under the new system always show up as cache.

**Comment by Chaphasilor** [comment] 2024-02-11 10:14
A migration shouldn't have taken place since the app had a signature, which should make updating (without uninstalling) impossible. I also tried to reproduce the issue, but for me it always ended up in the cache as well. I tried both MP3s and FLACs, and both as albums and playlists, with and without transcoding. So I think it's fine, unless @Fale manages to reproduce the issue?  
One thing that might be problematic with using the cache though might be [this](https://developer.android.com/training/data-storage/app-specific#internal-remove-cache). The cache directory can be cleared by the OS if space is low, which does make sense in our case (a few missing downloads won't hurt), but then we'll probably run into inconsistencies again. I saw no way to be informed about the cache clear, it just says to "check if the files exists before accessing them", which doesn't really help. What do you think?

I noticed another thing: the "clear cache" button on Android (within the system settings) doesn't work, it always goes back to the previous value and no data is actually deleted. I'm guessing that button invokes some callback within the platform code that we're not handling. But that is also fine for now, because if it would simply delete all downloads we'd run into inconsistencies between downloaded files and the Isar database.

**Comment by Komodo5197** [comment] 2024-02-11 23:24
Indeed, if the OS deletes a download we wouldn't notice until we try to play it and the file verification fails.  Hopefully that isn't something it'll actually do though.  Looking through the path provider code, this directory is coming out of applicationContext.getFilesDir() in the system libraries, which doesn't seem to actually be a cache directory, despite it showing as that in the settings.  And path_provider has get cache and temporary path methods that call down to applicationContext.getCacheDir(), which have warnings about the OS clearing out files in the android API reference that getFilesDir doesn't.  So hopefully the OS will not delete them.

**Comment by Chaphasilor** [comment] 2024-02-28 15:13
@Fale the download system has been improved as part of the redesign beta. Please let us know if this is still a problem! You can check it out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.

PS: you can now also use transcoded downloads to reduced the amount of space required on your device

**Closed by Chaphasilor** 2024-02-28 15:13 UTC
Labels: bug
