### ISSUE TITLE
Problem displaying song titles in grid mode

### ISSUE THREAD

**Issue by Onkornix** [jmshrv/finamp#373] opened 2022-12-28 01:49 UTC
In the songs tab it will correctly display the cover art but the song titles are completely wack.

What I see (iOS 16.2 iPhone XR)
https://imgur.com/a/M17Lu6t

**Comment by jmshrv** [comment] 2023-02-06 21:10
Apologies for missing this, this is a real issue that I can reproduce. Should we be displaying a list view in the songs tab?

**Comment by cmbarba** [comment] 2023-02-22 08:10
> Apologies for missing this, this is a real issue that I can reproduce. Should we be displaying a list view in the songs tab?

I think the songs tab should be a permanent list view because:

1. Tiled view focuses album/art and is unnecessary for list view which focuses song/title. If you want to focus on album/art just go to that tab
2. The songs tab will always benefit the most from list view over all other tabs for scrolling since it will always have the longest list

**Comment by Onkornix** [comment] 2023-03-02 01:41
> I think the songs tab should be a permanent list view because:
> 
>     1. Tiled view focuses album/art and is unnecessary for list view which focuses song/title. If you want to focus on album/art just go to that tab
> 
>     2. The songs tab will always benefit the most from list view over all other tabs for scrolling since it will always have the longest list

I agree with this.

**Comment by Onkornix** [comment] 2023-03-02 01:42
whoops lol. Didn't mean to close the issue. 
I'm very new to GitHub :/

**Comment by HamletDuFromage** [comment] 2023-03-05 22:06
Permanent list view for songs is usually the default music players, it does make little sense to do grid view imo. It may also be nice to do that for genres, or at least have the ability to set it as list view independently of albums/artists

**Comment by jmshrv** [comment] 2024-06-03 16:17
Looks like this was fixed a few months ago, closing

**Closed by jmshrv** 2024-06-03 16:17 UTC

**Comment by Terrance** [comment] 2024-06-03 21:37
I assume this is only fixed in the redesign beta?

Fine if so, just checking there isn't a regression here -- I'm on 0.6.23 and still see the grid layout as pictured above.

**Comment by Chaphasilor** [comment] 2024-06-03 21:49
Yes, seems to be beta-only. Sorry about that!

If you really need it I can probably fix this in stable too...

**Comment by Terrance** [comment] 2024-06-03 22:01
In my case it's very much a nice-to-have, so I wouldn't worry too much -- I use the list view layout normally as I tend to browse songs more than I do albums (where the grid view is nicer, but all the screens share the same layout setting).

**Comment by Chaphasilor** [comment] 2024-06-03 22:36
Sure you can! If you enable grid view, that will apply to all tabs except for songs/tracks :)

**Comment by HamletDuFromage** [comment] 2024-06-03 22:45
> Sure you can! If you enable grid view, that will apply to all tabs except for songs/tracks :)

Ah yes, my bad!
