### ISSUE TITLE
Ascending sort button not working on artist view

### ISSUE THREAD

**Issue by basings** [jmshrv/finamp#163] opened 2021-12-22 09:34 UTC
The up/down button ascending/descending sorting orter does not work on artist view. Neither on Genre view. But it works on songs and album view :)

**Comment by basings** [comment] 2021-12-22 09:34
v0.5.1

**Comment by rom4nik** [comment] 2022-02-27 22:18
I assume you're running server version 10.7.7 or older, which doesn't have https://github.com/jellyfin/jellyfin/pull/5929 and https://github.com/jellyfin/jellyfin/pull/6094 merged: https://github.com/jellyfin/jellyfin/commits/release-10.7.z/Jellyfin.Api/Controllers/ArtistsController.cs. This seems to be the reason.

**Comment by Chaphasilor** [comment] 2022-08-22 23:40
@basings is this still an happening?

**Comment by jmshrv** [comment] 2022-08-22 23:56
I can't reproduce this issue, going to close as it was a Jellyfin issue

**Closed by jmshrv** 2022-08-22 23:56 UTC
