### ISSUE TITLE
[BUG] Italian identified as RTL language while it's LTR

### ISSUE THREAD

**Issue by I-G-1-1** [jmshrv/finamp#313] opened 2022-08-26 16:11 UTC
since update to 0.6.6 the app interface for Italian is RTL while should be LTR.

![IMG_20220825_093140.jpg](https://user-images.githubusercontent.com/96726059/186947736-532f6bb0-ea1c-49c0-8c58-14b13de9f765.jpg)

**Comment by jmshrv** [comment] 2022-08-26 16:30
Does your device have any other languages set? It looks like it's picked up Arabic for some reason

**Comment by I-G-1-1** [comment] 2022-08-26 16:40
> Does your device have any other languages set? It looks like it's picked up Arabic for some reason 

Only English and Italian. I really don't know why picked up Arabic and inverted the interface to RTL.

**Comment by jmshrv** [comment] 2022-08-26 16:41
I'll try to reproduce the issue in a bit, this is very weird

**Comment by MrPotatoBobx** [comment] 2022-08-26 17:17
Are you using MiUI?

I reproduced it(changed system language to italian) and the same thing occurred. Not sure if its a finamp issue, android issue or just specific to MiUI.

**Comment by alaincao** [comment] 2022-08-27 06:41
FYI, same thing here.
I'm in french on LineageOS 18.1

**Comment by I-G-1-1** [comment] 2022-08-27 06:55
> Are you using MiUI?

Yes, I'm using MIUI 12.5.2

**Comment by MrPotatoBobx** [comment] 2022-08-27 12:40
Okay so i tested a bunch of languages out, and the ones that the app doesn't have translations for default to Arabic instead of English(the original language).

The languages that do not have this issue are the ones that are translated in version 0.6.6 [listed here](https://github.com/jmshrv/finamp/releases/tag/0.6.6)

**Comment by jmshrv** [comment] 2022-08-27 15:43
That's some interesting behaviour, I'll have a look to see if there's a way to set a default locale

**Comment by jmshrv** [comment] 2022-08-27 15:49
Should be fixed in b7876a1, will test in a minute

**Comment by jmshrv** [comment] 2022-08-27 16:30
Fix confirmed, will make a release at some point

**Closed by jmshrv** 2022-08-27 16:30 UTC
