### ISSUE TITLE
[Bug] removing songs from a downloaded playlist makes it so you can't remove those songs from your device.

### ISSUE THREAD

**Issue by drazil100** [jmshrv/finamp#76] opened 2021-07-16 06:22 UTC
I did some testing on what would happen if I removed songs from a playlist after downloading that playlist with finamp and as I guessed the songs that were removed stayed downloaded. I then downloaded the album those songs were part of and deleted the downloads and those songs remained on my device but the song that was still in the playlist was removed. I then added the songs that were still on my device back to the playlist on the server and downloaded them again and deleted the downloads but those 2 songs are still on my device.

**Comment by drazil100** [comment] 2021-07-16 08:07
> I then downloaded the album those songs were part of and deleted the downloads and those songs remained on my device but the song that was still in the playlist was removed.

Correction the song that was still in the playlist was deleted cause I had already deleted the download of the playlist. Small detail but figure id specify.

**Comment by UnicornsOnLSD** [comment] 2021-07-16 13:32
This should be fixed when I implement syncing, and I'm going to add some options to the download screen to delete downloads.

**Comment by jmshrv** [comment] 2022-10-09 17:40
Closing as a duplicate of #97

**Closed by jmshrv** 2022-10-09 17:40 UTC
