### ISSUE TITLE
[Redesign] Songs without cover art unplayable

### ISSUE THREAD

**Issue by RealStickman** [jmshrv/finamp#638] opened 2024-03-16 09:14 UTC
Songs without cover art can't be played at all. Instead, a different song with cover art starts playing.  
In my playlist with 3 songs lacking covers, the other song played is always the one 3 songs below.  
When playing a playlist, songs without covers won't be added to the list either, and using "next up" has no effect.  

See this video demonstration  

https://github.com/jmshrv/finamp/assets/61015582/69f4d956-5559-4a57-8bb0-a1383e35f165

Finamp version: 0.9.3-beta

**Comment by RealStickman** [comment] 2024-03-16 10:59
I noticed just now that the song offset will be kept for other songs below those without cover art.  
I.e. after 3 songs without cover art, every selection plays the song 3 places after. After a 4th song without cover art it's always 4 spaces and if not enough songs come after, the first song is selected.

Another video demonstration:  

https://github.com/jmshrv/finamp/assets/61015582/7ee34c7e-42d2-4f90-9b66-a6e13957b7e4

**Comment by Chaphasilor** [comment] 2024-03-16 21:38
Thanks for the report. This is a duplicate of #608, and will be fixed with the next beta update. Hopefully I can get that done this weekend...

**Closed by Chaphasilor** 2024-03-16 21:38 UTC
