### ISSUE TITLE
[BUG] Multiple libraries don't show correctly

### ISSUE THREAD

**Issue by velamvela** [jmshrv/finamp#89] opened 2021-07-22 01:53 UTC
Having two libraries is causing issues, I have audiobooks and music

The audiobooks section doesn't show any files, doesn't list albums, but lists Artists(but with no files)

**Comment by UnicornsOnLSD** [comment] 2021-07-22 02:25
I'm going to add audiobook tabs since they do apparently use different media types, I just assumed they would go under "Audio". Multiple music libraries does work though.

**Comment by jmshrv** [comment] 2022-10-09 17:56
Closing as duplicate of #231

**Closed by jmshrv** 2022-10-09 17:56 UTC
