### ISSUE TITLE
Resume playback of songs

### ISSUE THREAD

**Issue by funkslovechild** [jmshrv/finamp#402] opened 2023-02-19 20:46 UTC
When finamp stops playback it doesn't remember the last song played or playback position. As someone who listens to DJ mixes it would be great if finamp resumed playback of the last song played or kept a history of played songs like VLC.

**Comment by jmshrv** [comment] 2023-02-19 22:19
Duplicate of #60

**Closed by jmshrv** 2023-02-19 22:19 UTC
