### ISSUE TITLE
Improve Download Progress/Error Description

### ISSUE THREAD

**Issue by ryanwwest** [jmshrv/finamp#415] opened 2023-03-04 22:40 UTC
I have ~1500 downloaded items, and the Downloads page makes it easy to see how many are complete, enqueued, and running. However, I have a single 'failed' download that won't complete, and by going to the 'Download Errors' page and clicking the 'refresh' button (which I think is supposed to retry the downloads), it says 'No redownloads needed'. I understand occasional errors, but I wish there was an option to see the full filename, title, filepath, or other identifiable information for the error. The 'Download ID' doesn't show up when I search the generated log file.

Perhaps the long list of albums and songs in the regular Downloads page is meant to help you determine which files are and aren't downloaded yet, but when they get really long, it gets quite cumbersome to manually tap each and look through to see if one of the songs is downloaded or not. It would be nice if there were a way to immediately see not only more information about failed downloads, but also about the currently enqueued and running downloads (as often I'll have 'enqueued' items for 10+ minutes and don't know what they are).

**Comment by ryanwwest** [comment] 2023-03-04 22:46
(My instinct when on the Downloads page is to touch the spot of the counts of complete, failed, enqueued, and running, in hopes of getting more details about _what_ those counts actually include. This doesn't have to be the way of showing more details, however. I do think that the Download Errors page should list more information for every error.)

**Comment by jmshrv** [comment] 2023-03-05 01:15
I'll have to have look at whether the download library keeps error info. It's weird that the redownload button isn't working as intended though.

**Comment by Y0ngg4n** [comment] 2023-06-18 09:45
@ryanwwest should be fixed now. Just wait for the next release :)

**Closed** 2023-10-02 23:56 UTC
