### ISSUE TITLE
Bug: Playlists not displaying when iOS Application is online (Regression)

### ISSUE THREAD

**Issue by clifter1** [jmshrv/finamp#524] opened 2023-11-02 15:34 UTC
I always have my Finamp application in offline mode.  Last week, I brought my App online (to sync new playlist updates).  I then noticed that the playlist section would show nothing "No items found".  I can login to my Jellyfin server and verify all my playlists exist.  If I take my App Offline again, the existing playlists I originally had on the App will then display again.

The same issue exists if I uninstall and re-install the App.  Both Server and App are on the latest versions:

Server:   10.8.11,  Linux X64 (Docker container)
Phone:    iPhone 13 Mini with IOS 16.6.1
App:        Finamp 0.6.19

Note:  At some point in the past few months, a server update did cause the playlist to vanish in a similar manner.  However, after updating to 10.8.11, the server playlist existed again.  My assumption is that a change in the server was fixed, and the playlist behavior was changed in some way as to cause a similar issue with the App playlist.

**Comment by againstpetra** [comment] 2023-11-03 11:37
I don't think this is a Finamp issue, it's a Jellyfin 10.8.11 issue: https://github.com/jellyfin/jellyfin/issues/10272

Workaround is to downgrade Jellyfin until 10.8.12 is release.

**Comment by jmshrv** [comment] 2023-11-03 12:30
Duplicate of #501

**Closed by jmshrv** 2023-11-03 12:30 UTC

**Comment by clifter1** [comment] 2023-11-03 13:24
@jmshrv and @againstpetra Thanks for the update!  Rolling my Jellfyin container back to 10.8.10 cleared up the issue!  Thanks again for the awesome app and time you all have put in!!!
