### ISSUE TITLE
Feedback, Beta 0.9.8

### ISSUE THREAD

**Issue by BloodyIron** [jmshrv/finamp#797] opened 2024-06-27 05:32 UTC
(this is in the Beta v0.9.8 Android client)

I'm playing an album, I have it set to loop the whole album and shuffle is on.

I switch to another album, and suddenly shuffle is now off. So I have to turn it back on.

Can we please have it so the shuffle setting is retained when switching albums or going to individual songs, etc?

**Comment by Chaphasilor** [comment] 2024-07-29 13:43
Closing as a duplicate of #818 :)

**Closed by Chaphasilor** 2024-07-29 13:43 UTC

**Comment by BloodyIron** [comment] 2024-07-29 16:13
Wouldn't that be a duplicate of this, since this was reported _BEFORE_ #818? I'd say close #818 as duplicate of this... @Chaphasilor

**Comment by Chaphasilor** [comment] 2024-07-29 16:48
Order doesn't matter, and the other issur had a more descriptive title and more discussion going on :)
