### ISSUE TITLE
[Feature Request] Merge artist page with album page

### ISSUE THREAD

**Issue by seniorm0ment** [jmshrv/finamp#180] opened 2022-01-18 10:09 UTC
Requesting the artist page be added, with the information about the artist, and the ability to view all their albums, genres associated with them, etc.

As well as the ability to shuffle all songs from an artist.

**Comment by UnicornsOnLSD** [comment] 2022-01-18 10:35
I was considering redesigning the artists screen to look more like the album screen. Artist shuffle is a duplicate of #35, so I'll rename this issue to just be about the artists page

**Comment by seniorm0ment** [comment] 2022-01-18 11:08
Yeah, it seems you mean similar to how the Jellyfin app displays it? I do like how it displays it. That's kinda my idea

**Comment by UnicornsOnLSD** [comment] 2022-08-04 20:44
From @florinsdestortedvision - we could show the artist/album description, and use the backdrop as a background for the info bit

**Comment by florinsdistortedvision** [comment] 2022-08-05 07:13
Good idea, similar to how Jellyfin already does this (mobile app and web).

**Comment by Chaphasilor** [comment] 2024-10-28 11:23
This has been part of the beta for a while now, and missing features (like #572) will be tracked separtely

**Closed by Chaphasilor** 2024-10-28 11:23 UTC
Labels: redesign-beta
