### ISSUE TITLE
Widget support

### ISSUE THREAD

**Issue by YamiYukiSenpai** [jmshrv/finamp#579] opened 2024-01-21 14:33 UTC
I use the Android client from F-Droid, and would love to have homescreen widget support.

I haven't tried the iOS app, but it'd be great to have that there as well.

**Comment by Chaphasilor** [comment] 2024-01-23 07:02
Duplicate of #156  
You can leave a comment there about iOS support :)

**Closed** 2024-01-23 07:03 UTC
