### ISSUE TITLE
Playlists are no longer displayed

### ISSUE THREAD

**Issue by Trenobol** [jmshrv/finamp#505] opened 2023-09-30 19:51 UTC
Hi
Playlists are no longer displayed (no item found). They are visible in the web version. Were created in Finamp
iOS 17.0.2
Finamp 0.6.16
![1696103400319](https://github.com/jmshrv/finamp/assets/118353130/338038ab-bb2d-4e5a-bf49-11a5db426431)
![IMG_0032](https://github.com/jmshrv/finamp/assets/118353130/c8adf23c-6f49-4fc1-831a-d9e47c0ab2b7)

**Comment by Chaphasilor** [comment] 2023-09-30 19:53
Duplicate of #501  
It's a problem with the latest version of Jellyfin, downgrading should help

**Closed** 2023-09-30 19:53 UTC
