### ISSUE TITLE
No mini-player on status bar or lock screen.

### ISSUE THREAD

**Issue by marios8543** [jmshrv/finamp#987] opened 2024-12-25 11:02 UTC
Hello, I'm not sure if this is an issue or it simply doesn't exist but while finamp plays in the background I cannot control it from the lock screen or from the status bar, I need to open the app to change songs etc. Notifications are turned on in the settings. Phone is Galaxy S24 (Android 14/One UI 6.1)

**Comment by MaxTheSpy** [comment] 2024-12-28 20:19
Im having the exact same problem on S24.

**Comment by jmshrv** [comment] 2024-12-29 09:45
Duplicate of #956

**Closed** 2024-12-29 09:45 UTC
