### ISSUE TITLE
Download sync not working (or PEBKAC)

### ISSUE THREAD

**Issue by JPinSPACE** [jmshrv/finamp#539] opened 2023-11-30 19:18 UTC
I have been eagerly awaiting the new "sync downloads" feature since I keep a long playlist of music that I often listen to on shuffle. In the past whenever I added new items to the list I had to delete it and redownload the entire thing, which was time consuming and kind of a hassle.

I updated to 0.6.18, used my PC to add some new songs to my playlist, and then tried to get the playlist to update on finamp but was unable to do so. I didn't see any UI option on the playlist itself. When I went to the Downloads screen I hit the circular arrows to try to trigger a sync and nothing happened.

Is something broken here or am I just being incredibly dense?

Thanks!

**Comment by JPinSPACE** [comment] 2023-12-01 21:54
Ahh, that update sounds great! But I actually did try this on the Downloads screen as well, without success. Is that method intended to work with playlists?

**Comment by shayaantx** [comment] 2023-12-04 00:33
@JPinSPACE 
> In the past whenever I added new items to the list I had to delete it and redownload the entire thing, which was time consuming and kind of a hassle.

After https://github.com/jmshrv/finamp/pull/534 you will get a sync button on playlist and albums where you can sync individual playlist. You should not need to delete/download flow anymore.

As for when you clicked "sync" on downloads page
>When I went to the Downloads screen I hit the circular arrows to try to trigger a sync and nothing happened.

That will attempt to take every downloaded parent (playlist/album/etc) and try to sync it, so it should work in your use case. Maybe try again after the PR gets merged, otherwise something else is going if your that button isn't working as intended

**Comment by JPinSPACE** [comment] 2023-12-10 03:19
@shayaantx 
Yep, it sounds like the button is not working as intended. I went to the "Downloads" page and clicked the sync button and nothing happened. I've tried this a few times and given it time in case it needed to process, but it never downloads the updated playlist.

But it sounds like this will be fixed in a future update, so for my use case at least, I'm all set. But someone might want to look into the sync button behavior.

**Closed** 2023-12-24 14:48 UTC
