### ISSUE TITLE
[Feature] Change play button and scrolling bar colors based on artwork

### ISSUE THREAD

**Issue by florinsdistortedvision** [jmshrv/finamp#309] opened 2022-08-22 17:49 UTC
The blurred album artwork update is nice but, I think, to complete the package play button and scrolling bar should also change based on the artwork itself. Ex : if artwork is pink, change those too to a shade of pink

**Comment by rom4nik** [comment] 2022-08-22 21:37
Duplicate of #208.

**Closed** 2022-08-22 21:48 UTC
