### ISSUE TITLE
Download errors that aren't removed when retry download

### ISSUE THREAD

**Issue by arthurlutz** [jmshrv/finamp#364] opened 2022-11-21 14:04 UTC
The new feature of "redownload" when failed downloads works great, kudos for this improvement. 

I now have another problem : I still have "12 failed". The list has and id as title, and below "Failed to get song from download ID". Clicking the reload button says "No redownloads needed".

**Comment by ryanwwest** [comment] 2023-03-04 22:47
I encountered a similar problem and included it here: https://github.com/jmshrv/finamp/issues/415

**Comment by Y0ngg4n** [comment] 2023-10-04 17:21
Asi i fink this is a duplicate of #415 i think we can close this then

**Comment by Chaphasilor** [comment] 2023-10-04 17:44
Right, thanks for the heads-up @Y0ngg4n 😁

**Closed** 2023-10-04 17:43 UTC
