### ISSUE TITLE
Feature request: when songs are added to a downloaded playlist, download the new songs

### ISSUE THREAD

**Issue by JPinSPACE** [jmshrv/finamp#443] opened 2023-05-01 18:57 UTC
With the current behavior if I have a downloaded playlist and then add more songs to that playlist in Jellyfin, those songs will not be present in Finamp when I go offline.

Desired behavior: Finamp checks for new songs on downloaded playlists and also downloads those songs.

**Comment by jmshrv** [comment] 2023-05-02 23:57
Duplicate of #38

**Closed by jmshrv** 2023-05-02 23:57 UTC
