### ISSUE TITLE
What about automatically caching songs?

### ISSUE THREAD

**Issue by basings** [jmshrv/finamp#185] opened 2022-01-19 10:04 UTC
E.g. the 1000 most played songs and/or favourites.

**Comment by meonkeys** [comment] 2022-02-24 22:06
How about just caching each song as it is played, and always playing songs from cache? If a cached copy doesn't exist, it can't be played offline. Sorry in advance if this is a silly suggestion, I haven't read the source to know for sure.

**Comment by UnicornsOnLSD** [comment] 2022-02-24 22:12
Caching songs as they play would be #90

**Comment by meonkeys** [comment] 2022-02-24 22:15
Ah! Yep, that's exactly what I was thinking of.

**Comment by jmshrv** [comment] 2023-01-03 23:34
Duplicate of #90

**Closed by jmshrv** 2023-01-03 23:34 UTC
