### ISSUE TITLE
Wrong Localization

### ISSUE THREAD

**Issue by jaysonwcs** [jmshrv/finamp#319] opened 2022-08-30 13:12 UTC
The Finamp installed on my Android Device, which is localized in brazilian portuguese, but the app is displaying in a right-to-left mode, as if it was localized in arabic.

![Screenshot_2022-08-30-09-24-55-439_com unicornsonlsd finamp redimensionado](https://user-images.githubusercontent.com/7007373/187445402-5f9e6460-c6cd-42af-8918-91e9d18b86a1.jpg)
![Screenshot_2022-08-30-09-24-31-640_com unicornsonlsd finamp redimensionado](https://user-images.githubusercontent.com/7007373/187445412-964bdbbf-78ee-4a29-8f20-7d7336a31f74.jpg)
![Screenshot_2022-08-30-09-24-27-332_com unicornsonlsd finamp redimensionado](https://user-images.githubusercontent.com/7007373/187445415-e6813c62-7409-4fec-9311-1eb108edd2f8.jpg)
![Screenshot_2022-08-30-09-25-03-899_com unicornsonlsd finamp redimensionado](https://user-images.githubusercontent.com/7007373/187445398-fb73da4a-cb87-4839-83d2-90a15eaa7eba.jpg)

I tried resetting the app, erasing all data, and even reinstalling and rebooting, but its still displaying in right-to-left mode.

**Comment by jmshrv** [comment] 2022-08-30 14:43
Duplicate of #314, updating to 0.6.7 or 0.6.8 will fix. 0.6.8 is currently in app review, although it was just denied for copyright infringement for like the third time. For now, you can get an APK from the [releases page](https://github.com/jmshrv/finamp/releases)

**Closed by jmshrv** 2022-08-30 14:43 UTC
