### ISSUE TITLE
FR: Faster scroll speed when using alphabet scroller

### ISSUE THREAD

**Issue by ryanwwest** [jmshrv/finamp#776] opened 2024-06-13 22:47 UTC
I have a lot of songs and albums, so when I'm on the Albums or Playlists tabs (but really any tab with the alphabet scroller on the right), when I jump from e.g. A to Z, it takes some time to actually arrive at Z while scrolling through all songs (5-15 seconds, and lags on Tracks with my Z Fold 3 with 12GB RAM). 

While the animation of scrolling is nice in theory, I wonder if it would be better to just instantly jump to the letter clicked on, which would also sidestep the seeming problem of loading tons of song names just to display them for 0-1 frames on screen as they get scrolled past. Or if we need to keep that, then some smarter visualization that takes max e.g. ~.3 seconds and skips loading some song titles on the path there. I _guess_ you could have an option to enable/disable, but that seems very small and insignificant for another config setting.

Finamp 0.9.7.

**Comment by Chaphasilor** [comment] 2024-06-15 20:39
Hey, this is a duplicate of #694 where I've already commented by this isn't easy to do :)

**Closed by Chaphasilor** 2024-06-15 20:39 UTC
