### ISSUE TITLE
Noticeably slow startup

### ISSUE THREAD

**Issue by Terrance** [jmshrv/finamp#574] opened 2024-01-11 22:37 UTC
When launching the app cold (from a reboot, after long enough that the system has killed it etc.), it takes 5-10 seconds from the logo disappearing (leaving a black screen) until the album list appears.

I can't say I noticed this delay when I first started using the app, but unfortunately I'm not sure when this became noticeable enough to become a minor annoyance.

Device is a OnePlus Nord CE, Android 13, running Finamp 0.6.18.

Logcat of the startup: [11_01-22-19-00_609.log](https://github.com/jmshrv/finamp/files/13909079/11_01-22-19-00_609.log)

Not sure there's much to glean from it though -- nothing logged when the app is ready, but events were:

- 22:19:09: app launched, black screen shortly after
- 22:19:17 / +8s: app ready to use
- 22:19:19 / +10s: tapped on an album

**Comment by Chaphasilor** [comment] 2024-02-14 16:54
Can you share some stats about your library? Did you change any setings? I'm not really able to reproduce the behavior...

A screen recording that shows exactly what is being shown when might also help :D

**Comment by Chaphasilor** [comment] 2024-02-14 16:59
Ahh that might be it! I've noticed it too before; I'll try downloading a few GB and starting the app up later

**Comment by Terrance** [comment] 2024-02-14 19:49
I just tried opening the app again but it inexplicably loaded in the much more reasonable 1 second or so, so I'm not sure what's changed since the initial report (I don't know when I first noticed the slowdown, but it had been happening consistently for a while before I reported).

If relevant, I spend almost all of the time in offline mode -- I did recently toggle online to download two more albums for offline play, and then toggle back offline, so I wonder if that cleared a crusty cache somewhere?

> Can you share some stats about your library?

From downloads screen: 2545 downloads, 1552 items, 312 images.  Android reports ~15GB storage in use.  About 15% of my music library is downloaded here.

> A screen recording that shows exactly what is being shown when might also help :D

There wasn't much to see: black screen with logo for half a  second, all-black screen for 5-10 seconds, then on to the album list once the app does load.  I'll grab a recording if it becomes reproducible again.

**Comment by Chaphasilor** [comment] 2024-02-14 21:46
Interesting. I definitely noticed some slowdown after having downloaded 1.7k songs, but the delay is happening on the splash screen with the logo, not on a fully black screen.  
Offline mode didn't have any observable effect either.

I'll try with a few more downloads later, but it might be that there was some bad state going on. Although I wouldn't expect toggling offline mode to fix any issues in that case...

**Comment by Chaphasilor** [comment] 2024-02-15 08:55
So even with about 7k downloaded songs in the old download system it didn't go beyond 5s for startup, and no black screen. It's a powerful phone though, so other phones might take a bit longer.  
With the new download system and 10k songs startup takes around 1s, so it seems like it's not getting any slower there.

So I guess this won't be a problem in the future anyway :)

**Comment by Chaphasilor** [comment] 2024-02-28 15:15
@Terrance the download system has been improved as part of the redesign beta. Please let me know if startup is still slow with the new version. You can check it out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.

**Closed by Chaphasilor** 2024-02-28 15:15 UTC
Labels: bug
