### ISSUE TITLE
Sleep timer does not disable the icon

### ISSUE THREAD

**Issue by Demian98** [jmshrv/finamp#262] opened 2022-07-05 22:27 UTC
When the sleep timer is stopping the playback, the icon does not change back to its original state.
So, whenever you want to enable the sleep timer again you will be asked before, if you want to cancel the sleep timer. But this makes no sence, as the sleep timer was already finished.

No big issue, just a small thing to make to this great app even better.

**Comment by trhodeos** [comment] 2022-07-12 19:00
Hey @Demian98, I just tried to repro in 0.6.3 on Android, but it seems to be working as intended:
steps:
* click sleep timer button
* type in `1` minute
* click OK
* wait one minute..
* Music stops, the icon goes back to an outlined moon, and the app _doesn't_ ask to cancel the sleep timer.. it goes straight to creating a new timer.

What version are you using? Any additional repro steps?

**Comment by Demian98** [comment] 2022-07-12 21:14
Hey @UnicornsOnLSD, I'm using Finamp Version 0.6.3 on Android 10 and used the exact same steps as you described. But for me it does not go back to the outlined moon.

I tired is some more times with 1 minute and it also makes no difference whether the songs are downloaded, streamed, the offline mode is enabled or disabled. Always the same result.

**Comment by Demian98** [comment] 2022-07-31 18:56
Are there any information I can provide you to solve this?
Still the same in 0.6.5

**Comment by UnicornsOnLSD** [comment] 2022-07-31 18:58
I'll have a look when I can, I tested a while ago and saw the same behaviour

**Comment by Chaphasilor** [comment] 2024-01-25 19:57
This will be fixed in the redesign beta :)

**Comment by Chaphasilor** [comment] 2024-02-28 13:47
@Demian98 is has been fixed as part of the redesign beta. Resuming playback after the sleep timer paused it will also no longer restart the timer. You can check it out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.

**Closed by Chaphasilor** 2024-02-28 13:47 UTC
