### ISSUE TITLE
Wrong version uploaded

### ISSUE THREAD

**Issue by mcbelisle** [jmshrv/finamp#499] opened 2023-09-23 23:13 UTC
Installed latest version but old version is installed on top of old version

**Comment by Chaphasilor** [comment] 2023-09-23 23:39
Installed from where (Play Store, F-Droid, etc.)? And which version? :)

**Comment by mcbelisle** [comment] 2023-09-23 23:43
Arm64.  617 is really  6.16

**Comment by Hudzenten10** [comment] 2023-09-25 21:43
This is the same problem as issue #494. I also have this problem. I am using obtanium to pull the GitHub release, but even if I manually download the 0.6.17 version from GitHub via a web browser and install the apk, when going to settings-->info it shows 0.6.16. This is the arm64 version.

**Comment by jmshrv** [comment] 2023-10-08 17:28
Closed as duplicate of #494

**Closed by jmshrv** 2023-10-08 17:28 UTC
