### ISSUE TITLE
Playing a song on iOS exits finamp.

### ISSUE THREAD

**Issue by catfrightening** [jmshrv/finamp#509] opened 2023-10-10 00:23 UTC
As soon as I play any song on the app it just quits. nothing in the logs help either, they look normal. I'm on iOS 17.1 could be that I'm on a beta but I'm not sure

**Comment by edgemangt** [comment] 2023-10-10 00:30
I was just about to submit an issue as well.  iPhone 15 pro on iOS 17.0.3 with Finamp 0.6.18.  I've tried deleting and reinstalling the app, and also changing from my home jellyfin server to https://demo.jellyfin.org.  Finamp crashes each time I try to play a song whether it's streaming or previously downloaded.

**Comment by jmshrv** [comment] 2023-10-10 01:36
Reproduced. I'll push a fix ASAP.

**Comment by jmshrv** [comment] 2023-10-10 01:40
Looks like [Impeller](https://docs.flutter.dev/perf/impeller) is crashing. I'll push a release that disables it for now.

**Comment by catfrightening** [comment] 2023-10-10 01:42
> o

Will this pushed to the App store asap?

**Comment by jmshrv** [comment] 2023-10-10 01:48
Impeller disabled in 40a3134. Pushing to the App Store now. Will close this issue once it passes through App Review.

**Comment by jmshrv** [comment] 2023-10-10 01:57
This appears to be caused by the `Slider` in `ProgressSlider` - https://github.com/flutter/flutter/issues/134009.

**Comment by jmshrv** [comment] 2023-10-10 02:00
Submitted to App Review now

**Comment by outtahere** [comment] 2023-10-10 05:11
Confirming this issue also occuring on iOS 16.7 with latest version 0.6.18 Finamp.

**Comment by jmshrv** [comment] 2023-10-10 07:48
Yep, it's a bug in Flutter. The progress bar is actually a slider in disguise, and removing the handle causes Flutter to crash on the new version.

0.6.19 is currently "Waiting for Review"

**Comment by jmshrv** [comment] 2023-10-10 09:38
In Review now

**Comment by jmshrv** [comment] 2023-10-10 09:42
Approved! You should be able to update now.

**Closed by jmshrv** 2023-10-10 09:42 UTC
