### ISSUE TITLE
[BUG] the shuffle all feature shuffles the content of all libraries in offline mode

### ISSUE THREAD

**Issue by kuflierl** [jmshrv/finamp#819] opened 2024-07-23 13:02 UTC
When in offline mode, the shuffle all button in the songs tab shuffles all songs from all libraries instead of just the current library.

Finamp 0.6.22 IOS 15 iPhone6s

**Comment by Chaphasilor** [comment] 2024-07-29 11:33
Can you try upgrading to the beta version through Testflight? You can find the download link on the [release page](https://github.com/jmshrv/finamp/releases). The download system there is much more advanced, and we won't we making changes to the old/stable download system anymore

**Comment by kuflierl** [comment] 2024-07-31 13:18
Alright, I will be testing the beta. The Ui still requires some getting used to but I will somehow manage. It does seem much more feature rich on first glance though.

**Comment by kuflierl** [comment] 2024-08-06 10:30
This issue still persists in TestFlight 0.9.9 (109).
I haven't cleared all app data before installing the TestFlight version, so it might be an old db issue.

**Comment by kuflierl** [comment] 2024-09-18 20:32
@Chaphasilor would you mind updating the tags?

**Comment by Chaphasilor** [comment] 2024-09-18 20:40
Sure. Didn't get to the issue yet.

I just confirmed that this issue also happens for me. I'll try to look into it.

**Comment by Chaphasilor** [comment] 2024-09-18 21:22
Turns out it was a very simple fix. Will be part of the next beta update!

**Comment by kuflierl** [comment] 2024-10-10 16:16
> Possibly a duplicate of #761 ?

No, this issue is about the audio shuffle feature and how it ignores library boundaries in offline mode (music queue). The other issue #761 is about a visual bug. They might be the product of a common piece of code in the back-end though i don't think so due to to the lack of correlation (I don't really experience issue #761 anymore, but i can reproduce #819 very reliably).

**Comment by Chaphasilor** [comment] 2024-11-13 07:54
This should be fixed in 0.9.12. Let me know if not!

**Closed by Chaphasilor** 2024-11-13 07:54 UTC
Labels: bug, stable-version, redesign-beta

**Comment by kuflierl** [comment] 2024-11-13 23:09
seems to be fixed, thanks for the great player :heart:

**Comment by andreasmolnardev** [comment] 2025-09-01 18:27
@Chaphasilor The shuffling appears to also shuffle across all libraries when I'm not offline. I'm on the latest Testflight Beta (v.0.9.12) on a MacBook Air M3. Should I open a new issue or is this somehow expected behaviour?

**Comment by lukaslindnermusic** [comment] 2025-09-01 19:12
@andreasmolnardev the latest Testflight Beta is v0.9.19! ;) 

At some point, I have fixed a few things related to results from multiple libraries. Maybe your problem was fixed as well.
Please do a quick test on the latest version and let us know 😊 Thanks!

**Comment by andreasmolnardev** [comment] 2025-09-01 21:29
@lukaslindnermusic Thanks for the quick response, just restarted for the updates and I'm on v0.9.19 now and it's unfortunately still using all libraries when shuffling through tracks (even one I've deselected in the "Select Music libraries" tab). Oh and it also depends how you shuffle, I've just discovered: When doing it via the "Shuffle all" button it's working as expected but because I like rearranging the queue I mostly tap on songs directly, then it's using my entire music collection to shuffle through. So it's generating the mix of a song using all tracks if i understand this correctly?

**Comment by andreasmolnardev** [comment] 2025-09-01 21:34
To be more precise, it seems like the issue I'm having is related to generating instant mixes - not the shuffling itself. I've seen you're already experimenting with other methods for generating an instant mix. Any other ways to change that behaviour in Jellyfin directly?

**Comment by lukaslindnermusic** [comment] 2025-09-01 21:51
ahh yes, the instant Mix... just took a quick look at the code, and it seems that we are using the instantMix api endpoint of jellyfin directly, and this api endpoint, and the api documemtation doesn't mention a parameter to reduce the mix to a specific library... so this seems to be a Jellyfin issue?

I have no idea if you can change some setting on Jellyfin Web or something, but I don't think so. I believe this is just a bug (or expected behaviour that doesnt match our take on libraries?) by Jellyfin.

One more reason to implement our own instant mix :P 

The button on the bottom right on the tracks tab is just shuffleing 250 (default value, change in Audio Service Settings) tracks, it is not creating an instant mix. Therefore, this Shuffle All button is respecting the library.

**Comment by kuflierl** [comment] 2025-09-01 22:45
Indeed, i also have this issue/feature. I honestly don't mind it. But this belongs in a separate issue since this doesn't pertain to the shuffle all feature.
