### ISSUE TITLE
0.6.3 - No playback of opus files while transcoding

### ISSUE THREAD

**Issue by Maxplosion** [jmshrv/finamp#247] opened 2022-06-06 13:26 UTC
after tbe most recent update to 0.6.3 I am not able to play any OPUS encoded files when transcoding is active (which I have active all the time with 256kbit setting).

All works fine with direct play.

I tried changing the Bitrate, but that did not work either.
Worked fine in previous version(s).

Samsung Fold 3, Android 12

**Comment by UnicornsOnLSD** [comment] 2022-06-06 15:25
Could you play a song and send logs?

**Comment by UnicornsOnLSD** [comment] 2022-06-06 16:34
That email got cut off, could you send it on pastebin or something? I've said it before but I need to improve the report process lol

**Comment by Maxplosion** [comment] 2022-06-06 16:49
I've sent you another mail with a pastebin.

**Comment by Maxplosion** [comment] 2022-07-29 07:59
quick update: still the same behavior in 0.6.5

[MusicPlayerBackgroundTask/SEVERE] 2022-07-29 09:00:51.080250: Player error code 0: Source error

I can send you another logfile if you need, but it seems like there are no big changes to the last one from 0.6.3 in it.

**Comment by jmshrv** [comment] 2023-02-24 01:33
I'm assuming this is a duplicate of #269, which is now fixed (although this issue is older, that issue should have been pointed to here 🙃)

**Closed by jmshrv** 2023-02-24 01:33 UTC

**Comment by Maxplosion** [comment] 2023-02-24 07:07
Just tested lowering the transcoding bitrate and it played the files that were not playing before. so yes seems like that also fixes this issue then.
